# Generated by Django 6.0.7 on 2026-07-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='Имя файла')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('downloaded_at', models.DateTimeField(verbose_name='Время скачивания')),
            ],
            options={
                'verbose_name': 'Скачанный файл',
                'verbose_name_plural': 'Скачанные файлы',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
